name: CI Pipeline

on: push

env:
  REPO_OWNER: ${{ secrets.REPO_OWNER }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

jobs:
  run-pipeline:
    name: Python Setup and Cache Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: Cache DVC Cache Directory
        uses: actions/cache@v3
        with:
          path: .dvc/cache
          key: dvc-cache-${{ hashFiles('dvc.lock', '.dvc/config') }}

      - name: run pipeline
        run: |
          dvc repro

      - name: Run model tests
        run: |
          python -m unittest tests/test_model.py

      - name: Promote model to production
        if: success()
        run: python scripts/promote_model.py

  flask-app-test:
    name: Flask App Test
    runs-on: ubuntu-latest
    needs: run-pipeline
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Use cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      
      - name: Install dependencies from cache
        run: |
          pip install --no-deps -r requirements.txt

      - name: Restore DVC Cache from Cache
        uses: actions/cache@v3
        with:
          path: .dvc/cache
          key: dvc-cache-${{ hashFiles('dvc.lock', '.dvc/config') }}
          restore-keys: |
            dvc-cache-
      
      - name: test flask app
        run: python -m unittest tests/test_flask_app.py